dynamic card with veg logo
WinstonPais/itadakimasu pull request #31
Opened 2021-01-14 11:54 UTC by Wilton-Dsouza

![Screenshot (54)](https://user-images.githubusercontent.com/58103652/10#29 587631-3127c700-568d-11eb-8ef6-e0eb0fa84e73.png)
![Screenshot (55)](https://user-images.githubusercontent.com/58103652/104587635-338a2100-568d-11eb-93b1-c9b4acbfedf3.png)
#29

2021-01-14 21:11 UTC, WinstonPais requested changes

2021-01-14 21:11 UTC, WinstonPais commented on src/Grid/Grid.js
> +            let reciparr=[[data['user1rep'],data['user2rep'],data['user3rep']],[data['user4rep'],data['user5rep'],data['user6rep']]];
Will making this variable const break the code? if not use const

2021-01-14 21:11 UTC, WinstonPais commented on src/Grid/Grid.js
>              console.log(data.val());
remove console log

2021-01-16 04:53 UTC, WinstonPais approved these changes

2021-01-16 16:17 UTC, vinstenleon approved these changes

2021-01-16 16:17 UTC, merged